# Generated by Django 5.0.3 on 2025-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=244)),
                ('class_room', models.CharField(max_length=244)),
                ('day_of_week', models.CharField(max_length=244)),
                ('forma', models.CharField(max_length=244)),
                ('students', models.TextField()),
                ('subject', models.CharField(max_length=244)),
                ('teacher', models.CharField(max_length=244)),
                ('cabinet', models.CharField(max_length=244)),
                ('link', models.CharField(max_length=244)),
                ('replace_teacher', models.CharField(max_length=244)),
                ('replace_link', models.CharField(max_length=244)),
            ],
        ),
    ]
